"""
Alerts & Incident Command API Routes — Phase 10.

Connects to the canonical database table `alerts` to provide:
- Real-time persisted system alerts generated by events
- Filtering by severity, status, source, habitation, and site
- Acknowledgement and resolution workflows with timestamp audit trails
- Deep links to associated habitations and relocation sites
"""
from flask import Blueprint, request, jsonify
from app.db.database import get_session_factory
from app.db.repository import Repository
from app.engines.alert_engine import AlertEngine

alerts_bp = Blueprint("alerts", __name__)


def _ensure_alerts_seeded(session):
    """If the alerts table is completely empty, run baseline system audit to seed initial alerts."""
    from app.db.models import Alert
    count = session.query(Alert).count()
    if count == 0:
        AlertEngine.audit_and_seed_system_alerts(session)



@alerts_bp.route("", methods=["GET"])
@alerts_bp.route("/list", methods=["GET"])
def list_alerts():
    """
    List all persisted alerts from the database.
    Supports query filters:
    - severity: CRITICAL, HIGH, WARNING, INFO, ALL
    - status: ACTIVE, UNACKNOWLEDGED, ACKNOWLEDGED, RESOLVED, ALL
    - source: FIELD_VERIFICATION, OPTIMIZER, SIMULATION, etc.
    - habitation_id: filter by specific habitation
    - site_id: filter by specific candidate site
    """
    Session = get_session_factory()
    session = Session()
    try:
        _ensure_alerts_seeded(session)

        severity = request.args.get("severity")
        status = request.args.get("status")
        source = request.args.get("source")
        hab_id = request.args.get("habitation_id")
        site_id = request.args.get("site_id")

        alerts = Repository.get_alerts(
            db=session,
            severity=severity,
            status=status,
            source=source,
            habitation_id=hab_id,
            site_id=site_id
        )

        all_alerts = Repository.get_alerts(db=session)

        summary = {
            "total": len(all_alerts),
            "critical": len([a for a in all_alerts if (a.severity or "").upper() == "CRITICAL"]),
            "high": len([a for a in all_alerts if (a.severity or "").upper() == "HIGH"]),
            "warning": len([a for a in all_alerts if (a.severity or "").upper() == "WARNING"]),
            "info": len([a for a in all_alerts if (a.severity or "").upper() == "INFO"]),
            "unacknowledged": len([a for a in all_alerts if not a.is_acknowledged and not a.is_resolved]),
            "resolved": len([a for a in all_alerts if a.is_resolved]),
        }

        return jsonify({
            "alerts": [Repository.alert_to_dict(a) for a in alerts],
            "total": len(alerts),
            "summary": summary,
        })
    finally:
        session.close()


@alerts_bp.route("/<alert_id>/acknowledge", methods=["PATCH", "POST"])
def acknowledge_alert(alert_id: str):
    """Acknowledge a specific alert."""
    Session = get_session_factory()
    session = Session()
    try:
        alert = Repository.acknowledge_alert(session, alert_id)
        if not alert:
            return jsonify({"error": f"Alert {alert_id} not found"}), 404

        session.commit()
        return jsonify({
            "status": "success",
            "message": f"Alert {alert_id} acknowledged.",
            "alert": Repository.alert_to_dict(alert),
        })
    finally:
        session.close()


@alerts_bp.route("/<alert_id>/resolve", methods=["PATCH", "POST"])
def resolve_alert(alert_id: str):
    """Mark a specific alert as resolved."""
    Session = get_session_factory()
    session = Session()
    try:
        alert = Repository.resolve_alert(session, alert_id)
        if not alert:
            return jsonify({"error": f"Alert {alert_id} not found"}), 404

        session.commit()
        return jsonify({
            "status": "success",
            "message": f"Alert {alert_id} resolved.",
            "alert": Repository.alert_to_dict(alert),
        })
    finally:
        session.close()


@alerts_bp.route("/acknowledge-all", methods=["PATCH", "POST"])
@alerts_bp.route("/notifications/read-all", methods=["PATCH", "POST"])
def acknowledge_all():
    """Acknowledge all unacknowledged alerts in bulk."""
    Session = get_session_factory()
    session = Session()
    try:
        count = Repository.acknowledge_all_alerts(session)
        session.commit()
        return jsonify({
            "status": "success",
            "acknowledged_count": count,
        })
    finally:
        session.close()


@alerts_bp.route("/<alert_id>/read", methods=["PATCH", "POST"])
def mark_alert_read(alert_id: str):
    """Backward-compatible endpoint: alias for acknowledge."""
    return acknowledge_alert(alert_id)


@alerts_bp.route("/notifications", methods=["GET"])
def list_notifications():
    """Returns unacknowledged / active alerts formatted as notifications."""
    Session = get_session_factory()
    session = Session()
    try:
        _ensure_alerts_seeded(session)
        active_alerts = Repository.get_alerts(session, status="ACTIVE")
        notifs = []
        for a in active_alerts:
            notifs.append({
                "id": a.id,
                "alert_id": a.id,
                "title": a.title,
                "message": a.description,
                "severity": (a.severity or "INFO").lower(),
                "category": a.type or "system",
                "is_read": bool(a.is_acknowledged),
                "created_at": a.created_at.isoformat() + "Z" if a.created_at else None,
            })
        return jsonify({
            "notifications": notifs,
            "total": len(notifs),
            "unread": len(notifs),
        })
    finally:
        session.close()


@alerts_bp.route("/notifications/count", methods=["GET"])
def notification_count():
    """Returns count of active / unacknowledged alerts for the global header badge."""
    Session = get_session_factory()
    session = Session()
    try:
        _ensure_alerts_seeded(session)
        active_alerts = Repository.get_alerts(session, status="ACTIVE")
        return jsonify({
            "unread": len(active_alerts),
            "total": len(active_alerts),
        })
    finally:
        session.close()


@alerts_bp.route("/rules", methods=["GET"])
def get_alert_rules():
    """Return all configured alert engine rules."""
    return jsonify({"rules": AlertEngine.get_rules()})


@alerts_bp.route("/audit", methods=["POST"])
def trigger_audit():
    """Trigger an on-demand audit scan of the canonical database state."""
    Session = get_session_factory()
    session = Session()
    try:
        created = AlertEngine.audit_and_seed_system_alerts(session)
        return jsonify({
            "status": "success",
            "message": f"Database audit complete. {len(created)} baseline alerts verified/refreshed.",
            "alerts_created": [Repository.alert_to_dict(a) for a in created]
        })
    finally:
        session.close()
